### ISSUE TITLE
Error cannot find module express

### ISSUE THREAD

**Issue by rstrapasson** [satriowisnugroho/instagram-auto-likes-comments#3]
Hi.
I am trying to run the app on raspbian and I receive this error.

module.js:327
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/Instagram/instagram-auto-likes-comments/app.js:1:79)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by muhammadsarwani026** [comment]
Ini gue run pake node app.js kok keluar gini ya ? Makasih bos

module.js:549
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\instagrambot\app.js:1:79)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by wisnugro** [comment]
@rstrapasson @sarwani123 you need to install dependencies first. try `npm install` or `yarn`
